#!/usr/bin/env python3
from __future__ import annotations
import json, os, re, sys, tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PAGES = ROOT / "src/pages"
MARKER = "// @generated by ores-api-docs for a *-web-server.rs page; DO NOT EDIT."
FORBIDDEN = ("lambda_runtime", "aws_lambda_events", "AWS_LAMBDA_RUNTIME_API", "google_cloud", "K_SERVICE", "$PORT", "azure_functions")
PARAM = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

def fail(msg: str) -> None:
    raise SystemExit(f"server-layout conformance failed: {msg}")

def require(cond: bool, msg: str) -> None:
    if not cond: fail(msg)

def segment_shape(seg: str, terminal: bool) -> str:
    if seg.startswith("[[...") and seg.endswith("]]" ):
        name = seg[5:-2]; require(bool(PARAM.fullmatch(name)), f"invalid optional catch-all {seg}"); require(terminal, f"catch-all must be final: {seg}"); return "{*?}"
    if seg.startswith("[...") and seg.endswith("]"):
        name = seg[4:-1]; require(bool(PARAM.fullmatch(name)), f"invalid catch-all {seg}"); require(terminal, f"catch-all must be final: {seg}"); return "{*}"
    if seg.startswith("[") and seg.endswith("]"):
        name = seg[1:-1]; require(bool(PARAM.fullmatch(name)), f"invalid dynamic segment {seg}"); return "{}"
    require(not any(c in seg for c in "[](){}"), f"reserved route syntax in {seg}")
    return seg

def schema_refs(node: object):
    if isinstance(node, dict):
        ref = node.get("$ref")
        if isinstance(ref, str):
            yield ref
        for value in node.values():
            yield from schema_refs(value)
    elif isinstance(node, list):
        for value in node:
            yield from schema_refs(value)

routing = tomllib.loads((ROOT / ".ores-routing.toml").read_text())
fs = routing["filesystem"]
require(fs.get("root") == "src/pages", "filesystem root drift")
require(fs.get("leaf") == "page.rs", "page leaf drift")
require(fs.get("generator_leaf") == "gen.rs", "gen leaf drift")
require(fs.get("lambda_leaf") == "lambda.rs", "lambda leaf drift")
require(fs.get("layout_leaf") == "layout.rs", "layout leaf drift")
require(fs.get("url_mapping") == "one_to_one", "URL mapping must remain one_to_one")
require(fs.get("route_groups") is False, "route groups must remain disabled")
layout = routing["layout"]
require(layout.get("inheritance") == "ancestor_chain" and layout.get("affects_url") is False, "layout inheritance drift")
require(routing["codegen"].get("generate_lambda_source") is True and routing["codegen"].get("lambda_provider_neutral") is True, "lambda codegen drift")

for required in [
    ROOT / "contracts/server-layout/v1/typespec/main.tsp",
    ROOT / "contracts/server-layout/v1/json-schema/server-layout.schema.json",
    ROOT / "contracts/server-layout/v1/tjsv/mapping.json",
]: require(required.is_file(), f"missing {required.relative_to(ROOT)}")
schema = json.loads((ROOT / "contracts/server-layout/v1/json-schema/server-layout.schema.json").read_text())
require(schema.get("$schema") == "https://json-schema.org/draft/2020-12/schema", "server-layout schema draft drift")
require(schema.get("x-ores-authority") == "independent-peer", "JSON Schema peer authority drift")
schema_id = schema.get("$id")
require(isinstance(schema_id, str) and schema_id.startswith("https://"), "server-layout schema needs an absolute HTTPS $id")
expected_root = f"{schema_id}#/$defs/WebServerLayoutContract"
require(schema.get("$ref") == expected_root, "server-layout schema root must select WebServerLayoutContract through $defs")
for ref in schema_refs(schema):
    require(ref.startswith(f"{schema_id}#/$defs/"), f"ambiguous or external server-layout $ref: {ref}")
    target = ref.removeprefix(f"{schema_id}#/$defs/")
    require(target in schema.get("$defs", {}), f"server-layout $ref points at missing $defs target: {target}")

shapes: dict[str, Path] = {}
if PAGES.exists():
    for current, dirs, files in os.walk(PAGES, followlinks=False):
        d = Path(current)
        for name in dirs + files:
            p = d / name
            require(not p.is_symlink(), f"symlink forbidden in page tree: {p.relative_to(ROOT)}")
        names = set(files)
        if {"gen.rs", "lambda.rs"} & names:
            require("page.rs" in names, f"generated/helper leaf without page.rs: {d.relative_to(ROOT)}")
        if "lambda.rs" in names:
            text = (d / "lambda.rs").read_text()
            require(text.splitlines()[:1] == [MARKER], f"lambda.rs is not generator-owned: {(d/'lambda.rs').relative_to(ROOT)}")
            for token in FORBIDDEN: require(token not in text, f"provider token {token!r} in {(d/'lambda.rs').relative_to(ROOT)}")
            require("fn main()" not in text, f"server lambda.rs must not own main(): {(d/'lambda.rs').relative_to(ROOT)}")
        if "page.rs" not in names: continue
        rel = d.relative_to(PAGES)
        parts = list(rel.parts)
        rendered = [segment_shape(seg, i == len(parts)-1) for i, seg in enumerate(parts)]
        shape = "/" if not rendered else "/" + "/".join(rendered)
        if shape in shapes: fail(f"route shape collision: {shapes[shape].relative_to(ROOT)} and {(d/'page.rs').relative_to(ROOT)} -> {shape}")
        shapes[shape] = d / "page.rs"

print(f"server-layout conformance: ok ({len(shapes)} page routes)")
