#!/usr/bin/env sh
set -eu
mode=${1:---full}; case "$mode" in --structural-only|--full) ;; *) exit 2;; esac
root="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"; cd "$root"
fail(){ echo "[routing-conformance] $*" >&2; exit 1; }
for dir in contracts conformance src/pages; do [ -d "$dir" ] && [ ! -L "$dir" ] || fail "$dir must be a real non-symlink directory"; done
[ -z "$(find contracts conformance src/pages -type l -print -quit)" ] || fail 'symlinks are forbidden in routing authority/evidence trees'
for path in contracts/typespec/server-filesystem-routing.tsp contracts/json-schema/server-filesystem-routing.schema.json contracts/examples/server-filesystem-routing.json .zpkg.toml zed-env.toml .zed/pre-install .zed/post-install .githooks/pre-commit .githooks/pre-push scripts/install-git-hooks.sh; do [ -f "$path" ] && [ ! -L "$path" ] || fail "missing lifecycle authority: $path"; done
[ "$mode" = --full ] || exit 0
command -v zed >/dev/null 2>&1 || fail 'zed is required for full routing admission'
out="${TMPDIR:-/tmp}/canonical-web-routing-$$"; trap 'rm -rf "$out"' EXIT INT TERM; mkdir -p "$out"
zed run tjsv check --typespec="$root/contracts/typespec/server-filesystem-routing.tsp" --schema="$root/contracts/json-schema/server-filesystem-routing.schema.json" --report="$out/report.json" --output-dir="$out/generated" --quiet
zed run ores-stack web sync --check
zed run ores-stack web lambda sync --check
find src/pages -type f -name page.rs -print | while IFS= read -r page; do
  dir=${page%/page.rs}; [ -f "$dir/lambda.rs" ] || fail "$dir missing generated lambda.rs"
  head -n 1 "$dir/lambda.rs" | grep -Fqx '// @generated by ores-api-docs for a *-web-server.rs page; DO NOT EDIT.' || fail "$dir/lambda.rs has wrong generator marker"
  [ ! -e "$dir/rpc.rs" ] || fail "$dir must not contain rpc.rs"
done
python3 scripts/verify-interface-dependency.py
cargo fmt --all -- --check
cargo test --workspace --all-targets --locked
cargo clippy --workspace --all-targets --locked -- -D warnings
